blog/urls.py
from django.conf.urls import url, include
from . import views 

urlpatterns = [
    url('^$', views.blog, name='blogs'),
    url('blog/(?P<pk>[0-9]+)/', views.BlogDetailView.as_view(), name="blogdetail"),
    url('addblog/', views.BlogAddView.as_view(), name="addblog"),
    url('^update/(?P<pk>[0-9]+)/(?P<blog_title>.+)/', views.BlogUpdateView.as_view(), name="updateblog"),
    url('^delete/(?P<pk>[0-9]+)/(?P<blog_title>.+)/', views.BlogDeleteView.as_view(), name="deleteblog"),
    url('like/(?P<pk>[0-9]+)/', views.LikeView, name="like"),
    url('comment/(?P<pk>[0-9]+)/', views.CommentView.as_view(), name="comment"),
    
    
    url('category/(?P<blog_category>.+)/', views.Category.as_view(), name="category"),

]

finalYear/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('blogs/', include("blog.urls")),
    path('news/', include("news.urls")),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('library/', include('library.urls')),
    
    
    
    
    path('home', views.home, name='home'),
    path('help', views.help, name='help'),
    path('about', views.about, name='about'),
    path('terms', views.terms, name='terms'),
    path('privacy', views.privacy, name='privacy'),
    path('contact', views.contact, name='contact'),

]+ static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url('^$', views.news, name='news'),
    url('(?P<pk>[0-9]+)/(?P<title>.+)/', views.NewsDetailView.as_view(), name="newsdetail"),
    url('category/(?P<category>.+)/', views.Category.as_view(), name="newscategory"),
    url('addnews/', views.NewsAddView.as_view(), name="addnews"),
    url('update/(?P<pk>[0-9]+)/', views.NewsUpdateView.as_view(), name="updatenews"),
    url('delete/(?P<pk>[0-9]+)/', views.NewsDeleteView.as_view(), name="deletenews"),
]

news/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse

# Create your models here.

category_choices = [("Local", "Local"),("World","World"), ('Campus', 'Campus')]


class News(models.Model):
    reporter = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    category = models.CharField(choices=category_choices, max_length=20)
    content = RichTextField() #use rich text editor here
    datePosted = models.DateField(("dd mm yyyy"), auto_now_add=True)
    header_image = models.ImageField(upload_to="media/news" )   
    
  
    
    def __str__(self):
        """returns the the title and author of the blog in the admin page"""
        return f"{self.title} | {self.reporter}"
    
    
    def get_absolute_url(self):
        """return the blog detail of the immediate blog posted"""
        return reverse('newsdetail', args=[self.pk,self.title])
    #     #return reverse('home')
    

library/news/forms.py
from django import forms
from .models import News

class PostForm(forms.ModelForm):

    class Meta:
        model = News
        fields = (
                  "title",
                  "category",
                  "content",
                  "header_image"
                  )
        
    title = forms.CharField(max_length=80, widget = forms.TextInput( attrs={'class': 'form-control'}))
    header_image = forms.ImageField(required=True)


    
    

news/forms.py
from django import forms
from .models import News

class PostForm(forms.ModelForm):

    class Meta:
        model = News
        fields = (
                  "title",
                  "category",
                  "content",
                  "header_image"
                  )
        
    title = forms.CharField(max_length=80, widget = forms.TextInput( attrs={'class': 'form-control'}))
    header_image = forms.ImageField(required=True)


    
    

library/news/views.py
from django.shortcuts import get_object_or_404, render
from django.urls.base import reverse_lazy
from django.views.generic import ListView,DetailView, DeleteView
from django.views.generic.edit import CreateView, UpdateView
from news.models import News
from . forms import PostForm

# Create your views here.


def news(request): 
    news = News.objects.all().order_by('datePosted')
    context={
        'news': news
    }
    return render(request, 'news/news.html', context )


class NewsDetailView(DetailView):
    """ this class show the detail of a news"""
    model = News
    template_name ="news/news-detail.html"
    
    
    def  get_context_data(self, **kwargs):
        context = super(NewsDetailView, self).get_context_data(**kwargs)
        
        # connects to the blog model and creates a blog object with the primary key 
        news_connected = get_object_or_404(News, pk=self.kwargs['pk'])
        
        category = news_connected.category
        others = News.objects.filter(category=category).order_by("datePosted").exclude(pk=self.kwargs['pk'])
        context['others'] = others 
        
        return context
    
    
class NewsAddView(CreateView):
    """used to create form and post a News with the same class"""
    model = News
    form_class = PostForm
    template_name="news/news_form.html"

    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class NewsUpdateView(UpdateView):
    """used to create form and edit a News with the same class"""
    model = News
    form_class = PostForm
    template_name="news/update_form.html"



class NewsDeleteView(DeleteView):
    """used to delete a news with the same class"""
    model = News
    template_name = "news/news-delete.html"
    fields = "__all__"
    success_url = reverse_lazy('news')





    
class Category(ListView):
    template_name="news/news.html"
    context_object_name = 'news'
    def get_queryset(self, *args, **kwargs):     
        category = self.kwargs["category"]
        print(category)
        return News.objects.filter(category=category)

news/views.py
from django.shortcuts import get_object_or_404, render
from django.urls.base import reverse_lazy
from django.views.generic import ListView,DetailView, DeleteView
from django.views.generic.edit import CreateView, UpdateView
from news.models import News
from . forms import PostForm

# Create your views here.


def news(request): 
    news = News.objects.all().order_by('datePosted')
    context={
        'news': news
    }
    return render(request, 'news/news.html', context )


class NewsDetailView(DetailView):
    """ this class show the detail of a news"""
    model = News
    template_name ="news/news-detail.html"
    
    
    def  get_context_data(self, **kwargs):
        context = super(NewsDetailView, self).get_context_data(**kwargs)
        
        # connects to the blog model and creates a blog object with the primary key 
        news_connected = get_object_or_404(News, pk=self.kwargs['pk'])
        
        category = news_connected.category
        others = News.objects.filter(category=category).order_by("datePosted").exclude(pk=self.kwargs['pk'])
        context['others'] = others 
        
        return context
    
    
class NewsAddView(CreateView):
    """used to create form and post a News with the same class"""
    model = News
    form_class = PostForm
    template_name="news/news_form.html"

    
    def form_valid(self, form):
        form.instance.reporter = self.request.user
        return super().form_valid(form)


class NewsUpdateView(UpdateView):
    """used to create form and edit a News with the same class"""
    model = News
    form_class = PostForm
    template_name="news/update_form.html"



class NewsDeleteView(DeleteView):
    """used to delete a news with the same class"""
    model = News
    template_name = "news/news-delete.html"
    fields = "__all__"
    success_url = reverse_lazy('news')





    
class Category(ListView):
    template_name="news/news.html"
    context_object_name = 'news'
    def get_queryset(self, *args, **kwargs):     
        category = self.kwargs["category"]
        print(category)
        return News.objects.filter(category=category)

templates/news/news-delete.html
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}

      {% if user.id == news.reporter.id %}
        
         <h1>Delete {{news.title}} ........</h1> 

         <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            are you sure you wannado this??? 
            <input type="submit" value="yes Delete"
            class="btn btn-dark">
         </form>
      {% else %}
         
         you are not supposed to be here
         <a href="{% url 'login' %}">Login</a> OR
         <a href="{% url 'signup' %}">Sign Up</a>
      {% endif %}
      
   {% else %}
       you are not supposed to be here
        <a href="{% url 'login' %}">Login</a> OR
        <a href="{% url 'signup' %}">Sign Up</a>

   {% endif %}

{% endblock content %}

templates/news/news.html
{% extends "base.html" %}


{% block content %}
<!-- Topics Menu Here -->
<div class="scrollmenu  mb-2 text-center">
    <a href='{% url "news" %}' type="button" class="btn btn-outline-secondary rounded-pill "
        style="width:6rem; height: 40px;">
        <p class="" style="text-align: center; font-size: 16px;  ">
            All</p>
    </a>
    <a href='{% url "newscategory" "Campus" %}' type="button" class="btn btn-outline-secondary rounded-pill "
        style="width:6rem; height: 40px;">
        <p class="" style="text-align: center; font-size: 16px;  ">
            Campus</p>
    </a>
    <a href='{% url "newscategory" "Local" %}' type="button" class="btn btn-outline-secondary rounded-pill "
        style="width:6rem; height: 40px;">
        <p class="" style="text-align: center; font-size: 16px;  ">
            Local</p>
    </a>
    <a href='{% url "newscategory" "Global" %}' type="button" class="btn btn-outline-secondary rounded-pill "
        style="width:6rem; height: 40px;">
        <p class="" style="text-align: center; font-size: 16px;  ">
            Global</p>
    </a>




</div>
<!-- End Topic Menu Here -->

<!-- Container -->
<div class="flex-container">

    <div class="flex-item-left">
        <div class="container d-flex justify-content-center">

           


            {% for news in news %}
            <div class="card col-lg-8  d-flex">
                <img src="{{news.header_image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <div class="d-flex">
                        <img src="{{news.reporter.profile.profile_picture.url}}" width="30" height='30'
                            class="rounded-circle" alt="">
                        <span class="m-1 fs-5">{{news.reporter.first_name|title}}
                            {{news.reporter.last_name|title}}</span>
                        <span
                            class="m-1 fs-5 col-4 col-lg-2 text-center rounded-pill bg-dark text-light">{{news.category}}</span>
                    </div>
                    <h3 class="card-title">{{news.title|title}}</h3>
                    <div class="d-flex justify-content-between">
                        <span class="flex-col d-flex justify-content-start  fs-5 ">{{news.datePosted}}</span>
                        <div class=" flex-col d-flex justify-content-end">
                            <a href="{% url 'newsdetail' news.id news.title %}"
                                class="btn btn-outline-dark rounded-pill">Read More</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}


        </div>
    </div>
    <!-- Right Static Container -->
    <div class="flex-item-right border-start">
        <div class="container">
            {% if user.groups.all.0.name == 'reporters' %}
            <a href="{% url 'addnews' %}">Add News</a>
            {% endif %}
            <div>
                <!-- Topics -->
                <h2 class="mb-1 text-center">
                    <font face="Segoe UI" size="4.5px" color="#A4A1A1">Topics</font>
                </h2>
                <div class="row align-items-center text-center">
                    <div class="col">
                        <a style="width: 90%;" class="btn btn-outline-dark rounded-pill m-2" href="{% url 'newscategory' 'Campus' %}">
                            <font face="Segoe UI" size="4px" color="#A4A1A1" class="mt-1">Campus
                            </font>
                        </a>
                        <a style="width: 90%;" class="btn btn-outline-dark rounded-pill m-2" href="{% url 'newscategory' 'Local' %}">
                            <font face="Segoe UI" size="4px" color="#A4A1A1" class="mt-1">Local
                            </font>
                        </a>
                        <a style="width: 90%;" class="btn btn-outline-dark rounded-pill m-2" href="{% url 'newscategory' 'Global' %}">
                            <font face="Segoe UI" size="4px" color="#A4A1A1" class="mt-1">Global
                            </font>
                        </a>
                    </div>
                </div>
            </div>
            <!-- end of Topics -->
        </div>


        <hr style='width:250px; margin: auto' class="mt-3 mb-">
        <!-- footer  here-->
        <div class="">
            <div class="row align-items-start">
                <div class="col">
                    <a href="" type="button" class="btn - rounded-pill m-1">Help</a>
                    <button type="button" class="btn  rounded-pill m-1">About</button>
                    <button type="button" class="btn  rounded-pill m-1">Terms</button>
                    <button type="button" class="btn  rounded-pill m-1">Privacy</button>

                    <button type="button" class="btn - rounded-pill m-1">Contact</button>
                    <button type="button" class="btn  rounded-pill m-1">Write</button>

                </div>
            </div>

        </div>
    </div>
    <!-- footer here -->
</div>

<!-- End of Right Static Container -->
</div>

</div>
</div>
<!-- end of Container -->


<style>
    div.scrollmenu {
        overflow: auto;
        white-space: nowrap;
        padding: 5px 0px 5px 0px;
        height: 60px;
    }

    /* This pen */
    .light {
        background: #f3f5f7;
    }

    a,
    a:hover {
        text-decoration: none;
        transition: color 0.3s ease-in-out;
    }

    #pageHeaderTitle {
        margin: 2rem 0;
        text-transform: uppercase;
        text-align: center;
        font-size: 2.5rem;
    }



    @media screen and (max-width: 600px) {
        .flex-item-right {
            visibility: hidden;
            display: none;
        }
    }



    @media screen and (min-width: 769px) {
        div.scrollmenu {
            visibility: hidden;
            display: none;
        }

        .flex-container {
            display: flex;
            flex-direction: row;
        }

        .flex-item-left {
            padding: 10px;
            width: 80%;
            margin-left: 5%;
        }

        .flex-item-right {
            /* background-color:azure; */
            position: fixed;
            width: 20%;
            height: 900px;
            left: 75%;
            font-family: sans-serif;
        }

        .vl {
            border-left: 1px solid #A5A5A5;
            height: 750px;
            position: fixed;
            left: 69%
        }

        .flex-news-card {
            display: flex;
            flex-direction: row;
            font-size: 30px;
            text-align: center;
            margin-left: 20%;
            margin-right: 15%;
            width: 550px;
        }


        .grid-container {
            display: grid;
            grid-template-columns: auto auto auto auto;
            grid-gap: 10px;
            background-color: #2196F3;
            padding: 10px;
        }

        .grid-container>div {
            background-color: rgba(255, 255, 255, 0.8);
            text-align: center;
            padding: 20px 0;
            font-size: 30px;
        }




    }
</style>
{% endblock content %}

{% block script %}
<script>
    const boxes = document.querySelectorAll(".box");

    window.addEventListener("scroll", checkBoxes);

    checkBoxes();

    function checkBoxes() {
        const triggerBottom = (window.innerHeight / 5) * 4;

        boxes.forEach((box) => {
            const boxTop = box.getBoundingClientRect().top;

            if (boxTop < triggerBottom) {
                box.classList.add("show");
            } else {
                box.classList.remove("show");
            }
        });
    }

</script>
{% endblock script %}

templates/news/news_form.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}

<div class="container">
   <h1 class="text-center">Write News......</h1>
   <h6>All inputs are required *</h6>
   <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      
      <span>Title:</span>
      {{form.title}}
      
    
      <div class="row">
         <div class="col col-lg-6 col-md-6 col-12 mb-2">
            <span>Category:</span>
            {{form.category}}
         </div>
      </div>
      
      <h6>Content:</h6>
      {{ form.content }}
      {{ form.media }}
      
      
      
      
      <h5><span>Add Header Picture</span></h5>
      <div class="border-bottom border-start border-dark border-end p-2 mb-3">
         <div class="image-input">
            {{ form.header_image }}
            <img src="https://s3.amazonaws.com/37assets/svn/1667-jz-avatar-blue.png" class="image-preview">
            <label for="id_header_image" style="font-size: large;" class="btn btn-outline-dark rounded-pill  text-center image-button"><i class="fa fa-upload"></i>Upload File</label>
            <span style=" font-size: large; width: 50%;" class="btn btn-outline-dark rounded-pill change-image"><i class="fa fa-recycle"></i>Different file?</span>
         </div>
      </div>

      <button type="submit" class="rounded-button login-cta text-center"> Add Blog </button>
   </form>
</div>

{% else %}
you are not supposed to be here
<a href="{% url 'login' %}">Login</a> OR
<a href="{% url 'signup' %}">Sign Up</a>

{% endif %}

<style>


   :root {
      --bodybg: #dcdefe;
      --primary-color: #5138ee;
      --grey: #d6d6d6;
      --placeholder: #969696;
      --white: #fff;
      --text: #333;
      --slider-bg: #eff3ff;
      --login-cta-hover: #333;
   }







   .image-input {
      display: flex;
  align-items: center;
  justify-content: center;
   }

   .image-input input {
      display: none;
   }

   .image-input label {
      display: block;
      padding: .3rem .6rem;
      font-size: 115%;
      cursor: pointer;
      width: 50%;
   }

   .image-input label i {
      font-size: 125%;
      margin-right: .3rem;
   }

   .image-input label:hover i {
      animation: shake .35s;
   }

   .image-input img {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 180px;
      height: 180px;
   }

   .image-input span {
      display: none;
      text-align: center;
      cursor: pointer;
   }

   @keyframes shake {
      0% {
         transform: rotate(0deg);
      }

      25% {
         transform: rotate(10deg);
      }

      50% {
         transform: rotate(0deg);
      }

      75% {
         transform: rotate(-10deg);
      }

      100% {
         transform: rotate(0deg);
      }
   }

   .image-input a{
      display: none;
      visibility: hidden;
   }
   .image-input{
      font-size: 0px;
   }

   

   .profile_pic {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 180px;
      height: 180px;
      border-radius: 50%;
   }

   .login-cta {
      color: var(--white);
      text-decoration: none;
      border: 1px solid var(--login-cta-hover);
      margin: 25px 0 35px;
      background: var(--login-cta-hover);
   }

   .login-cta:hover {
      background: var(--login-cta-hover);
   }

   .rounded-button {
      display: flex;
      width: 60%;
      margin-left: 15%;
      text-decoration: none;
      border-radius: 50px;
      padding: 13px 20px;
      box-sizing: border-box;
      justify-content: center;
      font-size: 14px;
      font-weight: 500;
      align-items: center;
      transition: linear 0.2s;
   }

   .rounded-button:hover {
      box-shadow: 0px 0px 4px 0px var(--grey);
   }

   h5 {
      width: 100%;
      text-align: left;
      border-bottom: 1px solid #000;
      line-height: 0.1em;
      margin: 10px 0 0px;
   }

   h5 span {
      background: #fff;
      padding: 0 10px;
   }

   @media only screen and (min-width: 799px) {
      .container {
         width: 50rem;
      }
   }

   @media only screen and (max-width: 500px) {
      .container {
         width: 100%;
      }
   }

   .container input:focus {
      outline: none;
      border: 1px solid var(--primary-color);
   }

   .container input {
      padding: 13px 20px;
      box-sizing: border-box;
      border: 1px solid var(--grey);
      border-radius: 50px;
      font-family: sans-serif;
      font-weight: 500;
      font-size: 14px;
      color: var(--text);
      transition: linear 0.2s;
      width: 100%;
   }
   .container select {
      padding: 13px 20px;
      box-sizing: border-box;
      border: 1px solid var(--grey);
      border-radius: 50px;
      font-family: sans-serif;
      font-weight: 500;
      font-size: 14px;
      color: var(--text);
      transition: linear 0.2s;
      width: 100%;
   }


   .container input ::-webkit-input-placeholder {
      color: var(--placeholder);
      font-weight: 300;
      font-size: 14px;
   }

   .form-control:focus {
      box-shadow: none;
   }

   span {
      background: var(--white);
      z-index: 1;
      position: relative;
      padding: 0 10px;
      font-size: 14px;
   }
   #cke_id_content[style*="width: 835px"] {
      width: auto !important;
   }

   .cke_reset {
      width: 100% !important;
   }

   @media only screen and (max-width: 500px) {
      #cke_id_content[style*="width: 835px"] {
         width: auto !important;
      }

      .cke_reset {
         width: 100% !important;
      }
   }
</style>
{% endblock content %}


{% block script %}

<script>
   $('#id_header_image').on('change', function () {
      $input = $(this);
      if ($input.val().length > 0) {
         fileReader = new FileReader();
         fileReader.onload = function (data) {
            $('.image-preview').attr('src', data.target.result);
         }
         fileReader.readAsDataURL($input.prop('files')[0]);
         $('.image-button').css('display', 'none');
         $('.image-preview').css('display', 'block');
         $('.change-image').css('display', 'block');
      }
   });

   $('.change-image').on('click', function () {
      $control = $(this);
      $('#id_header_image').val('');
      $preview = $('.image-preview');
      $preview.attr('src', '');
      $preview.css('display', 'none');
      $control.css('display', 'none');
      $('.image-button').css('display', 'block');
   });
</script>

{% endblock script %}

templates/news/update_form.html
{% extends "base.html" %}

{% block content %}

   {% if user.is_authenticated %}
      {% if user.id == news.reporter.id %}
            <div class="container">
               <h1 class="text-center">Update News ......</h1>
               <h6>All inputs are required *</h6>
               <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  
                  <span>Title:</span>
                  {{form.title}}
                  
                
                  <div class="row">
                     <div class="col col-lg-6 col-md-6 col-12 mb-2">
                        <span>Category:</span>
                        {{form.category}}
                     </div>                     
                  </div>
                  
                  <h6>Content:</h6>
                  {{ form.content }}
                  {{ form.media }}
                  
                  
                  
                  
                  <h5><span>Add Header Picture</span></h5>
                  <div class="border-bottom border-start border-dark border-end p-2 mb-3">
                     <div class="image-input">
                        {{ form.header_image }}
                        <img src="{{news.header_image.url}}" class="image-preview">
                        <label for="id_header_image" style="font-size: large;" class="btn btn-outline-dark rounded-pill  text-center image-button"><i class="fa fa-upload"></i>Upload File</label>
                        <span style=" font-size: large; width: 50%;" class="btn btn-outline-dark rounded-pill change-image"><i class="fa fa-recycle"></i>Different file?</span>
                     </div>
                  </div>
            
                  <button type="Submit" class="rounded-button login-cta text-center"> Update Blog </button>
               </form>
            </div>
         
      {% else %}
         you are not supposed to be here
         <a href="{% url 'login' %}">Login</a> OR
         <a href="{% url 'signup' %}">Sign Up</a>
      {% endif %}
   
   {% else %}
      you are not supposed to be here
      <a href="{% url 'login' %}">Login</a> OR
      <a href="{% url 'signup' %}">Sign Up</a>
   {% endif %}

   <style>


      :root {
         --bodybg: #dcdefe;
         --primary-color: #5138ee;
         --grey: #d6d6d6;
         --placeholder: #969696;
         --white: #fff;
         --text: #333;
         --slider-bg: #eff3ff;
         --login-cta-hover: #333;
      }
   
   
   
   
   
   
   
      .image-input {
         display: flex;
     align-items: center;
     justify-content: center;
      }
   
      .image-input input {
         display: none;
      }
   
      .image-input label {
         display: block;
         padding: .3rem .6rem;
         font-size: 115%;
         cursor: pointer;
         width: 50%;
      }
   
      .image-input label i {
         font-size: 125%;
         margin-right: .3rem;
      }
   
      .image-input label:hover i {
         animation: shake .35s;
      }
   
      .image-input img {
         display: block;
         margin-left: auto;
         margin-right: auto;
         width: 180px;
         height: 180px;
      }
   
      .image-input span {
         display: none;
         text-align: center;
         cursor: pointer;
      }
   
      @keyframes shake {
         0% {
            transform: rotate(0deg);
         }
   
         25% {
            transform: rotate(10deg);
         }
   
         50% {
            transform: rotate(0deg);
         }
   
         75% {
            transform: rotate(-10deg);
         }
   
         100% {
            transform: rotate(0deg);
         }
      }
   
      .image-input a{
         display: none;
         visibility: hidden;
      }
      .image-input{
         font-size: 0px;
      }
   
      
   
      .profile_pic {
         display: block;
         margin-left: auto;
         margin-right: auto;
         width: 180px;
         height: 180px;
         border-radius: 50%;
      }
   
      .login-cta {
         color: var(--white);
         text-decoration: none;
         border: 1px solid var(--login-cta-hover);
         margin: 25px 0 35px;
         background: var(--login-cta-hover);
      }
   
      .login-cta:hover {
         background: var(--login-cta-hover);
      }
   
      .rounded-button {
         display: flex;
         width: 60%;
         margin-left: 15%;
         text-decoration: none;
         border-radius: 50px;
         padding: 13px 20px;
         box-sizing: border-box;
         justify-content: center;
         font-size: 14px;
         font-weight: 500;
         align-items: center;
         transition: linear 0.2s;
      }
   
      .rounded-button:hover {
         box-shadow: 0px 0px 4px 0px var(--grey);
      }
   
      h5 {
         width: 100%;
         text-align: left;
         border-bottom: 1px solid #000;
         line-height: 0.1em;
         margin: 10px 0 0px;
      }
   
      h5 span {
         background: #fff;
         padding: 0 10px;
      }
   
      @media only screen and (min-width: 799px) {
         .container {
            width: 50rem;
         }
      }
   
      @media only screen and (max-width: 500px) {
         .container {
            width: 100%;
         }
      }
   
      .container input:focus {
         outline: none;
         border: 1px solid var(--primary-color);
      }
   
      .container input {
         padding: 13px 20px;
         box-sizing: border-box;
         border: 1px solid var(--grey);
         border-radius: 50px;
         font-family: sans-serif;
         font-weight: 500;
         font-size: 14px;
         color: var(--text);
         transition: linear 0.2s;
         width: 100%;
      }
      .container select {
         padding: 13px 20px;
         box-sizing: border-box;
         border: 1px solid var(--grey);
         border-radius: 50px;
         font-family: sans-serif;
         font-weight: 500;
         font-size: 14px;
         color: var(--text);
         transition: linear 0.2s;
         width: 100%;
      }
   
   
      .container input ::-webkit-input-placeholder {
         color: var(--placeholder);
         font-weight: 300;
         font-size: 14px;
      }
   
      .form-control:focus {
         box-shadow: none;
      }
   
      span {
         background: var(--white);
         z-index: 1;
         position: relative;
         padding: 0 10px;
         font-size: 14px;
      }
      #cke_id_content[style*="width: 835px"] {
         width: auto !important;
      }
   
      .cke_reset {
         width: 100% !important;
      }
   
      @media only screen and (max-width: 500px) {
         #cke_id_content[style*="width: 835px"] {
            width: auto !important;
         }
   
         .cke_reset {
            width: 100% !important;
         }
      }
   </style>
{% endblock content %}


{% block script %}

<script>
   $('#id_header_image').on('change', function () {
      $input = $(this);
      if ($input.val().length > 0) {
         fileReader = new FileReader();
         fileReader.onload = function (data) {
            $('.image-preview').attr('src', data.target.result);
         }
         fileReader.readAsDataURL($input.prop('files')[0]);
         $('.image-button').css('display', 'none');
         $('.image-preview').css('display', 'block');
         $('.change-image').css('display', 'block');
      }
   });

   $('.change-image').on('click', function () {
      $control = $(this);
      $('#id_header_image').val('');
      $preview = $('.image-preview');
      $preview.attr('src', '');
      $preview.css('display', 'none');
      $control.css('display', 'none');
      $('.image-button').css('display', 'block');
   });
</script>

{% endblock script %}