blog/urls.py
from django.conf.urls import url, include
from . import views 

urlpatterns = [
    url('^$', views.blog, name='blogs'),
    url('blog/(?P<pk>[0-9]+)/', views.BlogDetailView.as_view(), name="blogdetail"),
    url('addblog/', views.BlogAddView.as_view(), name="addblog"),
    url('^update/(?P<pk>[0-9]+)/(?P<blog_title>.+)/', views.BlogUpdateView.as_view(), name="updateblog"),
    url('^delete/(?P<pk>[0-9]+)/(?P<blog_title>.+)/', views.BlogDeleteView.as_view(), name="deleteblog"),
    url('like/(?P<pk>[0-9]+)/', views.LikeView, name="like"),
    url('comment/(?P<pk>[0-9]+)/', views.CommentView.as_view(), name="comment"),
    
    
    url('category/(?P<blog_category>.+)/', views.Category.as_view(), name="category"),

]

finalYear/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('blogs/', include("blog.urls")),
    path('news/', include("news.urls")),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('library/', include('library.urls')),
    
    
    
    
    path('home', views.home, name='home'),
    path('help', views.help, name='help'),
    path('about', views.about, name='about'),
    path('terms', views.terms, name='terms'),
    path('privacy', views.privacy, name='privacy'),
    path('contact', views.contact, name='contact'),

]+ static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url, include
from django.urls.conf import path
from . views import CreateProfileView, EditProfileView, ShowProfileView, UpdateUserDetails, PasswordChange, sendMail, signup,activate
from django.contrib.auth import views as auth_views



urlpatterns = [    
        # url('signup/', UserSignUp.as_view(), name='signup'),
        url('signup/', signup, name='signup'),
        path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',  activate, name='activate'),  
        url('edit-usersettings/', UpdateUserDetails.as_view(), name='edit-usersettings'),
        url('accounts/', include('django.contrib.auth.urls')),
        path('accounts/', include('allauth.urls')),
        
        url('(?P<pk>[0-9]+)/createprofile/', CreateProfileView.as_view(), name="create_profile"),
        url('(?P<pk>[0-9]+)/profile/', ShowProfileView.as_view(), name="show_profile"),
        url('(?P<pk>[0-9]+)/editprofile/', EditProfileView.as_view(), name="edit_profile"),

        path('accounts/', include('social_django.urls', namespace='social')), 
        
        url('(?P<pk>[0-9]+)/send/', sendMail, name="send"),


]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.urls import reverse
# Create your models here.


class Profile(models.Model):
    # personal
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=600)
    profile_picture= models.ImageField(upload_to="media/profile" )
    telephone = models.CharField(max_length=13, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    work = models.CharField(max_length=70, null=True, blank=True)
    work_address = models.CharField(max_length=100, null=True, blank=True)
    
    # personal links
    whatsapp_number = models.CharField(max_length=100, null=True, blank=True)
    facebook_link = models.CharField(max_length=100, null=True, blank=True)
    twitter_link = models.CharField(max_length=100, null=True, blank=True)
    personal_website_link = models.CharField(max_length=100, null=True, blank=True)
    
    
    # top 3 skills
    skill_one = models.CharField(max_length=50, null=True, blank=True)
    skill_two = models.CharField(max_length=50, null=True, blank=True)
    skill_three = models.CharField(max_length=50, null=True, blank=True)
    
    # highest education
    highest_education = models.CharField(max_length=50, null=True, blank=True)
    programme_majored =  models.CharField(max_length=100, null=True, blank=True)
    
    def __str__(self):
        return str(self.user)
    

    def get_absolute_url(self):
        """return the blog detail of the immediate blog posted"""
        return reverse('show_profile', args=(str(self.pk)))
    
    

users/forms.py
from re import A
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm, UserCreationForm
from django import forms
from django.db.models import fields
from django.forms import widgets
from ckeditor.fields import RichTextField

from users.models import Profile


#this field changes the usercreation form from its default and adds the name and email fields to the signup form
class SignUpForm(UserCreationForm):
    email = forms.EmailField(widget= forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
#the widget changes the default styling to to a bootstrap default form stylings
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


#this functions enables us to change the the default username and password to deafult bootstrap form styling
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'





class EditUserForms(UserChangeForm):
    username = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget= forms.EmailInput(attrs={'class': 'form-control'}))
    
#the widget changes the default styling to to a bootstrap default form stylings
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',)





class PasswordChangeForms(PasswordChangeForm):
    old_password = forms.CharField(widget= forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(widget= forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(widget= forms.PasswordInput(attrs={'class': 'form-control'}))

    
#the widget changes the default styling to to a bootstrap default form stylings
    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')





class ProfileCreateForm(forms.ModelForm):
    
    
    class Meta:
        model = Profile
        fields  = [ "profile_picture",'bio',
                    "telephone", "address", "work","work_address",
                    "whatsapp_number", "facebook_link", "twitter_link","personal_website_link",
                    "skill_one", "skill_two", "skill_three",
                    "highest_education", "programme_majored"]
        
    
        widgets = {
            'bio' : forms.Textarea(attrs={'class':'form-control bio'}),
            'telephone' : forms.TextInput(attrs={'class':'form-control telephone' }),
            'address' : forms.TextInput(attrs={'class':'form-control address' }),
            'work' : forms.TextInput(attrs={'class':'form-control work' }),
            'work_address' : forms.TextInput(attrs={'class':'form-control work-address' }),
            'whatsapp_number' : forms.TextInput(attrs={'class':'form-control whatsapp' }),
            'facebook_link' : forms.TextInput(attrs={'class':'form-control facebook' }),
            'twitter_link' : forms.TextInput(attrs={'class':'form-control twitter' }),
            'personal_website_link' : forms.TextInput(attrs={'class':'form-control twitter' }),
            'skill_one' : forms.TextInput(attrs={'class':'form-control skill' }),
            'skill_two' : forms.TextInput(attrs={'class':'form-control skill' }),
            'skill_three' : forms.TextInput(attrs={'class':'form-control skill' }),
            'highest_education' : forms.TextInput(attrs={'class':'form-control education' }),
            'programme_majored' : forms.TextInput(attrs={'class':'form-control education' }),
        }
        
        
        
        

           

users/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm, UserChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse
from django.views.generic import CreateView
from django.urls.base import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView

from django.contrib.sites.shortcuts import get_current_site  
from django.template.loader import render_to_string  
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode  


from users.models import Profile
from . forms import EditUserForms, ProfileCreateForm, SignUpForm, PasswordChangeForms

from django.contrib.auth.models import User  
from django.contrib.auth import get_user_model

from django.utils.encoding import force_bytes, force_text  
from .tokens import account_activation_token  

from django.core.mail import EmailMessage, send_mail 
 
from django.http import HttpResponse 
# Create your views here.



# class UserSignUp(CreateView):
#     """Creates forms and allows user to register as a user"""
#     form_class = SignUpForm
#     template_name = 'registration/signup.html'
#     success_url = reverse_lazy('login')



class UpdateUserDetails(UpdateView):
    """creates forms and allow users to update their details"""
    form_class = EditUserForms

    template_name = 'users/updateuser.html'
    success_url = reverse_lazy('blogs')

    def get_object(self):
        return self.request.user


class PasswordChange(PasswordChangeView):
    """class for creating forms for users to change their passwords....
    currently not in use since this class is also provided by the allauth model"""
    form_class = PasswordChangeForms
    template_name = 'registration/password_change_form.html'
    success_url = reverse_lazy('edit_usersettings')
    
    

class CreateProfileView(CreateView):
    """class is used to create a profile for a new user"""
    model = Profile 
    template_name = "users/create_profile.html"
    form_class = ProfileCreateForm
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
   
   
   
    
    
class ShowProfileView(DetailView):
    """show the profile of blogger from the bog detail"""
    model = Profile
    template_name = 'users/profile.html'

    
    
    def  get_context_data(self, **kwargs):

        context = super(ShowProfileView, self).get_context_data(**kwargs)
        
        page_user = get_object_or_404(Profile, id=self.kwargs['pk'])
        context["page_user"] = page_user
        return context
    

def sendMail(request, **kwargs):
    pk = kwargs['pk']
    profile = get_object_or_404(Profile, pk=pk)
    user_email = profile.user.email
    print(profile, user_email, pk)
    if request.method == "POST":
        message =  request.POST['message']
        name = request.POST['name']
        subject1 = request.POST['subject']
        email = request.POST['email']
        subject = (f"Hi, you got a mail from {name} {email}. Subject: {subject1}")
        send_mail(
        subject,
        message,       
        email,
        [user_email],
        fail_silently=False,
        )   

    return HttpResponseRedirect(reverse('show_profile', args=[str(pk),]))
    

class EditProfileView(UpdateView):
    """class for creating forms for users to edit their profiles """
    model = Profile
    form_class = ProfileCreateForm
    template_name = 'users/edit_profile.html'
    # fields = ["bio","profile_picture", "telephone", "address", "work", ]
    
    
 


def signup(request):  
    """function for creating forms to add users then sends a verification link to the email of the user"""
    if request.method == 'POST':  
        form = SignUpForm(request.POST)  
        if form.is_valid():  
            # save form in the memory not in database  
            user = form.save(commit=False)  
            user.is_active = False  
            user.save()  
            # to get the domain of the current site  
            current_site = get_current_site(request)  
            mail_subject = 'Activation link has been sent to your email id'  
            message = render_to_string('users/acc_active_email.html', {  
                'user': user,  
                'domain': current_site.domain,  
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),  
                'token':account_activation_token.make_token(user),  
            })  
            to_email = form.cleaned_data.get('email')  
            email = EmailMessage(  
                        mail_subject, message, to=[to_email]  
            )  
            email.send()  
            return render(request, 'users/activate_email.html', {})
    else:  
        form = SignUpForm()  
    return render(request, 'registration/signup.html', {'form': form})  




def activate(request, uidb64, token): 
    """function that activates the users account when they
    click on the activation link sent to their email""" 
    User = get_user_model()  
    try:  
        uid = force_text(urlsafe_base64_decode(uidb64))  
        user = User.objects.get(pk=uid)  
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):  
        user = None  
    if user is not None and account_activation_token.check_token(user, token):  
        user.is_active = True  
        user.save()  
        return render(request, 'users/activate_success.html', {})  
    else:  
        return HttpResponse('Activation link is invalid!')  

templates/users/acc_active_email.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,  
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}  
{% endautoescape %}

templates/users/activate_email.html
{% extends 'base.html' %}


{% block content %}

<div class="alert alert-secondary" role="alert">
    Please confirm your email address to complete the registration
</div>






{% endblock %}

templates/users/activate_success.html
{% extends 'base.html' %}


{% block content %}

<h2>Thank you for your email confirmation. Now you can login your account.</h2>
<p>
  <a href="{% url 'login' %}"> You may login here</a>
</p>






{% endblock %}

templates/users/create_profile.html
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}


<div class="container">
   <!-- <img src="{{user.profile.profile_picture.url}}"> use if else to choose image for the profile pic -->
   <h2 class="text-center">Create A New Profile .......</h2>

   <div class="form-group">
      <form method="POST" enctype="multipart/form-data">
         {% csrf_token %}
         <h5><span>Add Profile Picture</span></h5>
         <div class="border-bottom border-start border-dark border-end p-2 mb-3">
            <div class="image-input">
               {{ form.profile_picture }}
               <img src="https://s3.amazonaws.com/37assets/svn/1667-jz-avatar-blue.png" class="image-preview">
               <label for="id_profile_picture" class="btn btn-outline-dark rounded-pill text-center image-button"><i class="fa fa-upload"></i>Upload File</label>
               <span style=" font-size: large; width: 50%;" class="btn btn-outline-dark rounded-pill change-image"><i class="fa fa-recycle"></i>Different file?</span>
            </div>
         </div>

         <h6>Tell Us About Yourself<i class="bi bi-emoji-wink"></i><i class="bi bi-hand-thumbs-up"></i>:</h6>
         {{ form.bio }}

         <h5><span>Work and School</span></h5>
         <div class="border-bottom border-start border-dark border-end p-2 ">
            <div class="row">
               <div class="col col-lg-6 col-md-6 col-12 mb-2">
                  <span>Telephone:</span>
                  {{form.telephone}}
               </div>
               <div class="col col-lg-6 col-md-6 col-12 mb-2">
                  <span>Address:</span>
                  {{form.address}}
               </div>
            </div>
            <div class="row">
               <div class="col col-lg-6 col-md-6 col-12 mb-2">
                  <span>Work/Student:</span>
                  {{form.work}}
               </div>
               <div class="col col-lg-6 col-md-6 col-12 mb-2">
                  <span>Company/School:</span>
                  {{form.work_address}}
               </div>
            </div>
         </div>

         <h5><span>Social</span></h5>
         <div class="border-bottom border-start border-dark border-end p-2 ">
            <div class="row">
               <div class="col col-lg-6 col-md-6 col-12 mb-2">
                  <span><i class="fa fa-internet-explorer" aria-hidden="true"></i>
                     Personal Website Link:</span>
                  {{ form.personal_website_link }}
               </div>
               <div class="col col-lg-6 col-md-6 col-12 mb-2">
                  <span><i class="bi bi-whatsapp"></i> WhatsApp Number:</span>
                  {{ form.whatsapp_number }}
               </div>
            </div>
            <div class="row">
               <div class="col col-lg-6 col-md-6 col-12 mb-2">
                  <span><i class="bi bi-facebook"></i>Facebook Link:</span>
                  {{ form.facebook_link }}
               </div>
               <div class="col col-lg-6 col-md-6 col-12 mb-2">
                  <span><i class="bi bi-twitter"></i>Twitter Link:</span>
                  {{ form.twitter_link }}
               </div>
            </div>
         </div>


         <h5><span>Education</span></h5>
         <div class="border-bottom border-start border-dark border-end p-2 ">
            <div class="row">
               <div class="col col-lg-6 col-md-6 col-12 mb-2">
                  <span><i class="fa fa-graduation-cap" aria-hidden="true"></i>
                     Highest Education:</span>
                  {{ form.highest_education }}
               </div>
               <div class="col col-lg-6 col-md-6 col-12 mb-2">
                  <span><i class="fa fa-leanpub" aria-hidden="true"></i>
                     Programme Majored:</span>
                  {{ form.programme_majored }}
               </div>
            </div>
         </div>

         <button type="submit" class="rounded-button login-cta text-center"> Create Profile </button>


         <!-- <div class="text-center" style="width: 80px;">
            <input type="submit" value="Update" class="btn btn-outline-dark">
         </div> -->
      </form>
   </div>

</div>











{% else %}
you are not supposed to be here
or not the correct user to edit
<a href="{% url 'login' %}">Login</a> OR
<a href="{% url 'signup' %}">Sign Up</a>
{% endif %}


<style>
   :root {
      --bodybg: #dcdefe;
      --primary-color: #5138ee;
      --grey: #d6d6d6;
      --placeholder: #969696;
      --white: #fff;
      --text: #333;
      --slider-bg: #eff3ff;
      --login-cta-hover: #333;
   }



   .image-input {
      display: flex;
  align-items: center;
  justify-content: center;
   }

   .image-input input {
      display: none;
   }

   .image-input label {
      display: block;
      padding: .3rem .6rem;
      font-size: 115%;
      cursor: pointer;
      width: 50%;
   }

   .image-input label i {
      font-size: 125%;
      margin-right: .3rem;
   }

   .image-input label:hover i {
      animation: shake .35s;
   }

   .image-input img {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 180px;
      height: 180px;
      border-radius: 50%;
   }

   .image-input span {
      display: none;
      text-align: center;
      cursor: pointer;
   }

   @keyframes shake {
      0% {
         transform: rotate(0deg);
      }

      25% {
         transform: rotate(10deg);
      }

      50% {
         transform: rotate(0deg);
      }

      75% {
         transform: rotate(-10deg);
      }

      100% {
         transform: rotate(0deg);
      }
   }







   #id_profile_picture input[type="file"] {
      padding: 13px 20px;
      box-sizing: border-box;
      border: 0px solid var(--grey);
      border-radius: 1px;
      font-family: sans-serif;
      font-weight: 400;
      font-size: 18px;
      color: blue;
   }


   .profile_pic {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 180px;
      height: 180px;
      border-radius: 50%;
   }

   .login-cta {
      color: var(--white);
      text-decoration: none;
      border: 1px solid var(--login-cta-hover);
      margin: 25px 0 35px;
      background: var(--login-cta-hover);
   }

   .login-cta:hover {
      background: var(--login-cta-hover);
   }

   .rounded-button {
      display: flex;
      width: 60%;
      margin-left: 15%;
      text-decoration: none;
      border-radius: 50px;
      padding: 13px 20px;
      box-sizing: border-box;
      justify-content: center;
      font-size: 14px;
      font-weight: 500;
      align-items: center;
      transition: linear 0.2s;
   }

   .rounded-button:hover {
      box-shadow: 0px 0px 4px 0px var(--grey);
   }

   h5 {
      width: 100%;
      text-align: left;
      border-bottom: 1px solid #000;
      line-height: 0.1em;
      margin: 10px 0 0px;
   }

   h5 span {
      background: #fff;
      padding: 0 10px;
   }

   @media only screen and (min-width: 799px) {
      .container {
         width: 50rem;
      }
   }

   @media only screen and (max-width: 500px) {
      .container {
         width: 90%;
      }
   }

   .container input:focus {
      outline: none;
      border: 1px solid var(--primary-color);
   }

   .container input {
      padding: 13px 20px;
      box-sizing: border-box;
      border: 1px solid var(--grey);
      border-radius: 50px;
      font-family: sans-serif;
      font-weight: 500;
      font-size: 14px;
      color: var(--text);
      transition: linear 0.2s;
   }

   .container input ::-webkit-input-placeholder {
      color: var(--placeholder);
      font-weight: 300;
      font-size: 14px;
   }

   .form-control:focus {
      box-shadow: none;
   }
   @media only screen and (min-width: 799px) {
      .bio {
         height: 200px; 
         }
   }
   @media only screen and (max-width: 799px) {
      .bio {
         height: 350px; 
         }
   }

   .bio {
      border-radius: 50px;
      padding: 20px 20px 20px 20px;
   }

   span {
      background: var(--white);
      z-index: 1;
      position: relative;
      padding: 0 10px;
      font-size: 14px;
   }
</style>

{% endblock content %}

{% block script %}
<script>
   $('#id_profile_picture').on('change', function () {
      $input = $(this);
      if ($input.val().length > 0) {
         fileReader = new FileReader();
         fileReader.onload = function (data) {
            $('.image-preview').attr('src', data.target.result);
         }
         fileReader.readAsDataURL($input.prop('files')[0]);
         $('.image-button').css('display', 'none');
         $('.image-preview').css('display', 'block');
         $('.change-image').css('display', 'block');
      }
   });

   $('.change-image').on('click', function () {
      $control = $(this);
      $('#id_profile_picture').val('');
      $preview = $('.image-preview');
      $preview.attr('src', '');
      $preview.css('display', 'none');
      $control.css('display', 'none');
      $('.image-button').css('display', 'block');
   });
</script>
{% endblock script %}

templates/users/updateuser.html
{% extends "base.html" %}

{% block content %}
<div class="container">

<h1>Update Settings .......</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p}}
<a class="btn btn-outline-dark rounded-pill" style="width: 60%;" href="{% url 'password_change' %}">Change Password</a>
<button type="submit" style="width: 30%;" class="btn btn-dark rounded-pill">Update</button>
</form>

</div>
<style>
    @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500&display=swap");
  
    :root {
      --bodybg: #dcdefe;
      --primary-color: #5138ee;
      --grey: #d6d6d6;
      --placeholder: #969696;
      --white: #fff;
      --text: #333;
      --slider-bg: #eff3ff;
      --login-cta-hover: #1f0098;
    }
  
    #id_password {
      visibility: hidden;
      display: none;
  }

  .helptext {
      visibility: hidden;
      display: none;
  }

  label[for="id_password"] {
      display: none;}

      @media only screen and (min-width: 799px) {
        .container {
           width: 50rem;
        }
     }
  
     @media only screen and (max-width: 500px) {
        .container {
           width: 90%;
        }
     }
  
     .container input:focus {
        outline: none;
        border: 1px solid var(--primary-color);
     }
  
     .container input {
        padding: 13px 20px;
        box-sizing: border-box;
        border: 1px solid var(--grey);
        border-radius: 50px;
        font-family: sans-serif;
        font-weight: 500;
        font-size: 14px;
        color: var(--text);
        transition: linear 0.2s;
     }
  
     .container input ::-webkit-input-placeholder {
        color: var(--placeholder);
        font-weight: 300;
        font-size: 14px;
     }
  
     .form-control:focus {
        box-shadow: none;
     }
    
  </style>

{% endblock content %}