blog/urls.py
from django.conf.urls import url, include
from . import views 

urlpatterns = [
    url('^$', views.blog, name='blogs'),
    url('blog/(?P<pk>[0-9]+)/', views.BlogDetailView.as_view(), name="blogdetail"),
    url('addblog/', views.BlogAddView.as_view(), name="addblog"),
    url('^update/(?P<pk>[0-9]+)/(?P<blog_title>.+)/', views.BlogUpdateView.as_view(), name="updateblog"),
    url('^delete/(?P<pk>[0-9]+)/(?P<blog_title>.+)/', views.BlogDeleteView.as_view(), name="deleteblog"),
    url('like/(?P<pk>[0-9]+)/', views.LikeView, name="like"),
    url('comment/(?P<pk>[0-9]+)/', views.CommentView.as_view(), name="comment"),
    
    
    url('category/(?P<blog_category>.+)/', views.Category.as_view(), name="category"),

]

finalYear/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('blogs/', include("blog.urls")),
    path('news/', include("news.urls")),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('library/', include('library.urls')),
    
    
    
    
    path('home', views.home, name='home'),
    path('help', views.help, name='help'),
    path('about', views.about, name='about'),
    path('terms', views.terms, name='terms'),
    path('privacy', views.privacy, name='privacy'),
    path('contact', views.contact, name='contact'),

]+ static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

library/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url('^$', views.library, name='library'),
    url('(?P<pk>[0-9]+)/(?P<title>.+)/', views.BookDetailView.as_view(), name="bookdetail"),
    url('addbook/', views.BookAddView.as_view(), name="addbook"),

   ]

library/models.py
from django.db import models
from .validators import validate_file_extension
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Library(models.Model):
    poster = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length = 50)
    author = models.CharField(max_length=300, null=True, blank=True)
    abstract = models.TextField(max_length = 1000)
    E_Book = models.FileField(upload_to="media/library", validators=[validate_file_extension])
    datePosted = models.DateField(("dd mm yyyy"), auto_now_add=True)
    book_cover = models.ImageField(upload_to="media/news" )

    # is_valid = models.BooleanField()
     
    class Meta:
        ordering = ['title']
     
    def __str__(self):
        return f"{self.title} | {self.poster}"
    
    def get_absolute_url(self):
        """return the blog detail of the immediate blog posted"""
        return reverse('bookdetail', args=[self.pk,self.title])

library/forms.py
from django import forms
from .models import Library

class PostForm(forms.ModelForm):

    class Meta:
        model = Library
        fields = (
                  "title",
                  "author",
                  "abstract",
                  "book_cover",
                  "E_Book"
                  )
        
    title = forms.CharField(max_length=80, widget = forms.TextInput( attrs={'class': 'form-control'}))
    author = forms.CharField(max_length=300, widget = forms.TextInput( attrs={'class': 'form-control'}))
    abstract = forms.CharField(max_length=1000, widget = forms.Textarea( attrs={'class': 'form-control'}))
    book_cover = forms.ImageField(required=True)


    
    

library/news/forms.py
from django import forms
from .models import News

class PostForm(forms.ModelForm):

    class Meta:
        model = News
        fields = (
                  "title",
                  "category",
                  "content",
                  "header_image"
                  )
        
    title = forms.CharField(max_length=80, widget = forms.TextInput( attrs={'class': 'form-control'}))
    header_image = forms.ImageField(required=True)


    
    

library/news/views.py
from django.shortcuts import get_object_or_404, render
from django.urls.base import reverse_lazy
from django.views.generic import ListView,DetailView, DeleteView
from django.views.generic.edit import CreateView, UpdateView
from news.models import News
from . forms import PostForm

# Create your views here.


def news(request): 
    news = News.objects.all().order_by('datePosted')
    context={
        'news': news
    }
    return render(request, 'news/news.html', context )


class NewsDetailView(DetailView):
    """ this class show the detail of a news"""
    model = News
    template_name ="news/news-detail.html"
    
    
    def  get_context_data(self, **kwargs):
        context = super(NewsDetailView, self).get_context_data(**kwargs)
        
        # connects to the blog model and creates a blog object with the primary key 
        news_connected = get_object_or_404(News, pk=self.kwargs['pk'])
        
        category = news_connected.category
        others = News.objects.filter(category=category).order_by("datePosted").exclude(pk=self.kwargs['pk'])
        context['others'] = others 
        
        return context
    
    
class NewsAddView(CreateView):
    """used to create form and post a News with the same class"""
    model = News
    form_class = PostForm
    template_name="news/news_form.html"

    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class NewsUpdateView(UpdateView):
    """used to create form and edit a News with the same class"""
    model = News
    form_class = PostForm
    template_name="news/update_form.html"



class NewsDeleteView(DeleteView):
    """used to delete a news with the same class"""
    model = News
    template_name = "news/news-delete.html"
    fields = "__all__"
    success_url = reverse_lazy('news')





    
class Category(ListView):
    template_name="news/news.html"
    context_object_name = 'news'
    def get_queryset(self, *args, **kwargs):     
        category = self.kwargs["category"]
        print(category)
        return News.objects.filter(category=category)

library/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView, DeleteView
from django.views.generic.edit import CreateView, UpdateView
from library.models import Library
from .forms import PostForm

# Create your views here.

def library(request):
    """ queries all blog from the database and sends a template based the device"""
    books = Library.objects.order_by('-datePosted')
    content = {
        "books" : books
    }
    return render(request, 'library/library.html', content)

class BookDetailView(DetailView):
    """ this class show the detail of a news"""
    model = Library
    template_name ="library/library-detail.html"
    context_object_name = 'book'


class BookAddView(CreateView):
    """used to create form and post a News with the same class"""
    model = Library
    form_class = PostForm
    template_name="library/library_form.html"

    
    def form_valid(self, form):
        form.instance.poster = self.request.user
        return super().form_valid(form)

templates/library/library-detail.html
{% extends "base.html" %}

{% block title %}
blog detail
{% endblock title %}

{% block content %}

<style>
  .author {
    display: flex;
    margin: 20px 0px 20px 0px;
  }

  .content {
    text-align: justify;
    font-family: Georgia, Cambria, "Times New Roman", Times, serif;
  }

  .like-comment {
    display: flex;
  }

  .like {
    display: flex;
    border: 1px solid grey;
  }

  .like span {
    margin-top: 3px;
    font-size: x-large;
    font-weight: 500;
    margin-right: 10px;
  }

  .comments {
    display: flex;
    border: 1px solid grey;
    margin-left: 10px;
    margin-right: 10px;
  }

  .comments span {
    font-weight: 500;
    margin-right: 10px;
  }

  .btn:focus {
    box-shadow: none;
  }

  @media screen and (max-width: 769px) {
    h2 {
      font-size: 1.9rem;
      font-weight: 800;
      text-align: justify;
    }

    .author img {
      border-radius: 50%;
      margin-right: 5px;
      width: 25px;
      height: 25px;
    }

    .username a {
      font-size: 1.0rem;
      font-weight: 500;
      text-decoration: none;
      color: rgba(41, 41, 41, 1);
      margin-right: 10px;

    }

    .dateread {
      margin-right: 5px;
      font-size: 0.9rem;
      color: rgb(66, 64, 64);
      margin-top: 2px;


    }

    .header-image {
      width: 100%;
      height: 400px;
    }

    .container {
      width: 100%;
      align-items: center;
      color: rgba(41, 41, 41, 1);
    }

    .edit {
      text-decoration: none;
      color: white;
      background-color: rgb(66, 64, 64);
      width: 80px;
      text-align: center;
      font-size: 1.0rem;
      height: 22px;
      font-family: sans-serif;
      margin-left: 10px;
      margin-right: 10px;
      margin-top: 4px;
    }

    .edit:hover {
      color: white;
    }

    .delete {
      text-decoration: none;
      color: white;
      background-color: rgb(66, 64, 64);
      ;
      width: 80px;
      text-align: center;
      font-size: 1.0rem;
      height: 22px;
      font-family: sans-serif;
      margin-top: 4px;
    }

    .delete:hover {
      color: white;
    }

    .edit-delete-pc {
      visibility: hidden;
      display: none;
    }

    .comment-input-pc {
      display: none;
      visibility: hidden;
    }

  }

  @media screen and (min-width: 769px) {
    .comment-input-mobile {
      display: none;
      visibility: hidden;
    }

    h2 {
      font-size: 2.5rem;
      font-weight: 700;
    }

    .container {
      width: 60%;
      align-items: center;
      color: rgba(41, 41, 41, 1);

    }

    .author img {
      border-radius: 50%;
      margin-right: 5px;
      width: 30px;
      height: 30px;
    }

    .username a {
      font-size: larger;
      font-weight: 500;
      color: rgba(41, 41, 41, 1);
      text-decoration: none;
      margin-right: 10px;
    }

    .dateread {
      margin-right: 5px;
      font-size: 0.9rem;
      color: rgb(66, 64, 64);
      margin-top: 6px;
    }

    .edit {
      text-decoration: none;
      color: white;
      background-color: rgb(66, 64, 64);
      width: 80px;
      text-align: center;
      font-size: 1.0rem;
      height: 22px;
      font-family: sans-serif;
      margin-left: 10px;
      margin-right: 10px;
      margin-top: 4px;
    }

    .edit:hover {
      color: white;
    }

    .delete {
      text-decoration: none;
      color: white;
      background-color: rgb(66, 64, 64);
      width: 80px;
      text-align: center;
      font-size: 1.0rem;
      height: 22px;
      font-family: sans-serif;
      margin-top: 4px;
    }

    .delete:hover {
      color: white;
    }


    .header-image {
      width: 100%;
      height: 400px;
    }

    .edit-delete-mobile {
      visibility: hidden;
      display: none;
    }

  }

  .sidebar {
    height: 100%;
    width: 0;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: white;
    overflow-x: hidden;
    transition: 0.5s;
    padding-top: 60px;
    padding-bottom: 80px;
    margin: 70px 5px 0px 5px;

    border-right: 1px solid gray;
  }

  .sidebar a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 25px;
    color: #818181;
    display: block;
    transition: 0.3s;
  }

  .sidebar a:hover {
    color: #f1f1f1;
  }

  .sidebar .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
  }



  #main {
    transition: margin-left .5s;
    padding: 16px;
  }

  /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
  @media screen and (max-height: 450px) {
    .sidebar {
      padding-top: 15px;
    }

    .sidebar a {
      font-size: 18px;
    }
  }
</style>
<div class="container main">

  <h2>{{book.title|title}}</h2>
  <h4>by {{book.author|title}}</h4>
  <div class="author">
    <img src="{{book.poster.profile.profile_picture.url}}" alt="">
    <span class="username"><a href="">{{book.poster.first_name|title}} {{book.poster.last_name|title}}</a></span>
    <span class="dateread">{{book.datePosted}}</span>

  </div>


  {% if book.book_cover.url %}
  <div>
    <img class="header-image" src="{{book.book_cover.url}}" alt="">
  </div>
  {% endif %}
  <div class="content">
    {{book.abstract | safe}}
  </div>

  <a class="btn btn-outline-dark rounded-pill" style="width: 100%;" href="{{book.E_Book.url}}">Read book Here</a>.</p>
  <hr>


  <div class="card mb-3 m-2 " style="max-width: 780px;align-items: center;">
    <div class="row g-0">
      <div class="col-md-4 mt-2 text-center">
        <img src="{{book.poster.profile.profile_picture.url}}" class="img-fluid"
          style="border-radius: 50%; width: 160px; height: 160px; align-items: center;" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{book.poster.first_name|title}} {{book.poster.last_name|title}}</h5>
          <div style="display: flex;" class="">
            {% if book.poster.profile.personal_website_link %}
            <a href="{{book.poster.profile.personal_website_link}}"
              style="margin-right: 10px; font-size: x-large; text-decoration: none; color:rgb(66, 64, 64);"
              class="fa fa-internet-explorer fa-large" aria-hidden="true"></a>
            {% endif %}
            {% if book.poster.profile.whatsapp_number %}
            <a href="https://web.whatsapp.com/send?phone={{book.poster.profile.whatsapp_number}}&amp;text="
              data-number="{{book.poster.profile.whatsapp_number}}"
              style="margin-right: 10px; font-size: x-large; text-decoration: none; color:rgb(66, 64, 64);"
              class="fa fa-whatsapp fa-large" aria-hidden="true">
            </a>
            {% endif %}
            {% if book.poster.profile.facebook_link %}
            <a href="{{book.poster.profile.facebook_link}}"
              style="margin-right: 10px; font-size: x-large; text-decoration: none; color:rgb(66, 64, 64);"
              class="fa fa-facebook-square fa-large" aria-hidden="true"></a>
            {% endif %}
            {% if book.poster.profile.twitter_link %}
            <a href="{{book.poster.profile.twitter_link}}"
              style="margin-right: 10px; font-size: x-large; text-decoration: none; color:rgb(66, 64, 64);"
              class="fa fa-twitter fa-large" aria-hidden="true"></a>
            {% endif %}
          </div>
          <p class="card-text">{{book.poster.profile.bio | truncatewords:20}} </p>
          <a class="card-text btn" href="{% url 'show_profile' book.poster.profile.id %}">View Profile <i
              class="fa fa-arrow-right"></i> </a>

        </div>
      </div>
    </div>
  </div>

</div>


<!-- 
<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
  {% if comments %}
  Comment{{ comments.count|pluralize }} {{total_comments}}
  <span class="badge badge-dark ml-2">{{ comments.count }}</span>
  {% for comment in comments %}
  <div class="mt-2">
    <div class="card p-2">
      <div class="col-12">
        <strong>{{ comment.name }}</strong>
      </div>
      <div class="col-12">
        <p class="m-1 mt-3">{{ comment.body }}</p>
        <p class="text-right text-muted"><small>{{ comment.created }}</small></p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endif %}
</div>
{% for other in others %}
  <div class="mt-2">
    <div class="card p-2">
      <div class="col-12">
        <strong>{{ other.blog_title }}</strong>
      </div>
      <div class="col-12">
        <p class="m-1 mt-3">{{ other.blog_description }}</p>
        <p class="text-right text-muted"><small>{{ other.blog_datePosted }}</small></p>
        <p class="text-right text-muted"><small>{{ other.blog_category }}</small></p>
      </div>
      <a href="{% url 'blogdetail' other.blog_Id %}">read more</a>
    </div>
  </div>
  {% endfor %} -->



{% endblock content %}

{% block script %}
<script>
  function openNav() {
    document.getElementById("mySidebar").style.width = "300px";
    document.getElementById("main").style.marginLeft = "350px";
  }

  function closeNav() {
    document.getElementById("mySidebar").style.width = "0";
    document.getElementById("main").style.marginLeft = "0";
  }
</script>
{% endblock script %}

templates/library/library.html
{% extends "base.html" %}


{% block content %}



<!-- Container -->
<div class="flex-container">

    <div class="flex-item-left d-flex justify-content-center row">


        <section class="cards-wrapper ms-5">
            {% for book in books %}
            <div class="card-grid-space">

                <a class="card" href="{% url 'bookdetail' book.id book.title %}"
                    style="--bg-img: url({{book.book_cover.url}})">
                    <div>
                        <h4>{{book.title|title}}</h4>
                        <h5 mt-> <i class="bi bi-person-fill"></i> {{book.author|title}}</h5>
                        <div class="date">Posted: {{book.datePosted}}</div>

                    </div>
                </a>
            </div>
            {% endfor %}

        </section>


    </div>
</div>
<!-- Right Static Container -->
<div class="flex-item-right border-start">
    <div class="container">
        
        <div>
            <!-- Topics -->
            
            <div class="row align-items-center text-center">
                <img src="https://ebookfriendly.com/wp-content/uploads/2013/06/Best-quotes-about-libraries-and-librarians-When-in-doubt-go-to-the-library-J.K.-Rowling-540x763.jpg"
                    alt="">
            </div>
        </div>
        <!-- end of Topics -->
    </div>


    <hr style='width:250px; margin: auto' class="mt-3 mb-">
    <!-- footer  here-->
    <div class="">
        <div class="row align-items-start">
            <div class="col">
                <a href="" type="button" class="btn - rounded-pill m-1">Help</a>
                <button type="button" class="btn  rounded-pill m-1">About</button>
                <button type="button" class="btn  rounded-pill m-1">Terms</button>
                <button type="button" class="btn  rounded-pill m-1">Privacy</button>

                <button type="button" class="btn - rounded-pill m-1">Contact</button>
                <button type="button" class="btn  rounded-pill m-1">Write</button>

            </div>
        </div>

    </div>
</div>
<!-- footer here -->
</div>

<!-- End of Right Static Container -->
</div>

</div>
</div>
<!-- end of Container -->


<style>
    /* This pen */




    @media screen and (max-width: 600px) {
        .flex-item-right {
            visibility: hidden;
            display: none;
        }
    }



    @media screen and (min-width: 769px) {


        .flex-container {
            display: flex;
            flex-direction: row;
        }

        .flex-item-left {
            width: 80%;
            margin-left: 5rem;
        }

        .flex-item-right {
            /* background-color:azure; */
            position: fixed;
            width: 20%;
            height: 900px;
            left: 80%;
            font-family: sans-serif;
        }

        .vl {
            border-left: 1px solid #A5A5A5;
            height: 750px;
            position: fixed;
            left: 69%
        }

    }

    :root {
        --color: #3c3163;
        --transition-time: 0.5s;
    }

    * {
        box-sizing: border-box;
    }



    a {
        color: inherit;
    }

    .cards-wrapper {
        display: grid;
        justify-content: center;
        align-items: center;
        grid-template-columns: 1fr 1fr 1fr;
        grid-gap: 1rem;
        width: max-content;
    }

    .card {
        font-family: 'Heebo';
        --bg-filter-opacity: 0.4;
        background-image: linear-gradient(rgba(0, 0, 0, var(--bg-filter-opacity)), rgba(0, 0, 0, var(--bg-filter-opacity))), var(--bg-img);
        height: 20em;
        width: 13em;
        font-size: 1.5em;
        color: white;
        border-radius: 1em;
        padding: 1em;
        /*margin: 2em;*/
        display: flex;
        align-items: flex-end;
        background-size: cover;
        background-position: center;
        box-shadow: 0 0 1em -1em black;
        transition: all, var(--transition-time);
        position: relative;
        overflow: hidden;
        border: 10px solid #ccc;
        text-decoration: none;
    }

    .card:hover {
        transform: rotate(0);
    }

    .card h4 {
        margin: 18rem 0 0 0;
        font-size: 1.0em;
        text-align: left;
        line-height: 0.9em;
    }

    .card h5 {
        font-size: 0.75em;
        font-family: 'Open Sans';
        margin-top: 0.5em;
        line-height: 2em;
    }

    .card .tags {
        display: flex;
    }

    .card .tags .tag {
        font-size: 0.75em;
        background: rgba(255, 255, 255, 0.5);
        border-radius: 0.3rem;
        padding: 0 0.5em;
        margin-right: 0.5em;
        line-height: 1.5em;
        transition: all, var(--transition-time);
    }

    .card:hover .tags .tag {
        background: var(--color);
        color: white;
    }

    .card .date {
        position: absolute;
        top: 0;
        right: 0;
        font-size: 0.75em;
        padding: 1em;
        line-height: 1em;
        opacity: .8;
    }

    .card:before,
    .card:after {
        content: '';
        transform: scale(0);
        transform-origin: top left;
        border-radius: 50%;
        position: absolute;
        left: -50%;
        top: -50%;
        z-index: -5;
        transition: all, var(--transition-time);
        transition-timing-function: ease-in-out;
    }

    .card:before {
        background: #ddd;
        width: 250%;
        height: 250%;
    }

    .card:after {
        background: white;
        width: 200%;
        height: 200%;
    }

    .card:hover {
        color: var(--color);
    }

    .card:hover:before,
    .card:hover:after {
        transform: scale(1);
    }

    .card-grid-space .num {
        font-size: 3em;
        margin-bottom: 1.2rem;
        margin-left: 0rem;
    }

    .info {
        font-size: 1.2em;
        display: flex;
        padding: 1em 3em;
        height: 3em;
    }

    .info img {
        height: 3em;
        margin-right: 0.5em;
    }

    .info h1 {
        font-size: 1em;
        font-weight: normal;
    }

    /* MEDIA QUERIES */
    @media screen and (max-width: 1285px) {
        .cards-wrapper {
            grid-template-columns: 1fr 1fr;
        }
    }

    @media screen and (max-width: 900px) {
        .cards-wrapper {
            grid-template-columns: 1fr;
        }

        .info {
            justify-content: center;
        }

        .card-grid-space .num {
            margin-left: 0;
            text-align: center;
        }
    }

    @media screen and (max-width: 500px) {


        .card {
            max-width: calc(100vw - 4rem);
        }
    }

    @media screen and (max-width: 450px) {
        .info {
            display: block;
            text-align: center;
        }

        .info h1 {
            margin: 0;
        }
    }
</style>
{% endblock content %}

{% block script %}
<script>
    const boxes = document.querySelectorAll(".box");

    window.addEventListener("scroll", checkBoxes);

    checkBoxes();

    function checkBoxes() {
        const triggerBottom = (window.innerHeight / 5) * 4;

        boxes.forEach((box) => {
            const boxTop = box.getBoundingClientRect().top;

            if (boxTop < triggerBottom) {
                box.classList.add("show");
            } else {
                box.classList.remove("show");
            }
        });
    }

</script>
{% endblock script %}

templates/library/library_form.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}

<div class="container">
   <h1 class="text-center">Write News......</h1>
   <h6>All inputs are required *</h6>
   <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      
      <span>Title:</span>
      {{form.title}}
      
    
            <span>Author:</span>
            {{form.author}}
        
      <div class="m-2">
      <h6>abstract:</h6>
      {{ form.abstract }}
      </div>

      <span>Choose Your E-Book</span>
      {{form.E_Book}}
      
      
      <h5><span>Add Book Cover</span></h5>
      <div class="border-bottom border-start border-dark border-end p-2 mb-3">
         <div class="image-input">
            {{ form.book_cover }}
            <img src="https://s3.amazonaws.com/37assets/svn/1667-jz-avatar-blue.png" class="image-preview">
            <label for="id_book_cover" style="font-size: large;" class="btn btn-outline-dark rounded-pill  text-center image-button"><i class="fa fa-upload"></i>Upload File</label>
            <span style=" font-size: large; width: 50%;" class="btn btn-outline-dark rounded-pill change-image"><i class="fa fa-recycle"></i>Different file?</span>
         </div>
      </div>

      <button type="submit" class="rounded-button login-cta text-center"> Post Book </button>
   </form>
</div>

{% else %}
you are not supposed to be here
<a href="{% url 'login' %}">Login</a> OR
<a href="{% url 'signup' %}">Sign Up</a>

{% endif %}

<style>


   :root {
      --bodybg: #dcdefe;
      --primary-color: #5138ee;
      --grey: #d6d6d6;
      --placeholder: #969696;
      --white: #fff;
      --text: #333;
      --slider-bg: #eff3ff;
      --login-cta-hover: #333;
   }







   .image-input {
      display: flex;
  align-items: center;
  justify-content: center;
   }

   .image-input input {
      display: none;
   }

   .image-input label {
      display: block;
      padding: .3rem .6rem;
      font-size: 115%;
      cursor: pointer;
      width: 50%;
   }

   .image-input label i {
      font-size: 125%;
      margin-right: .3rem;
   }

   .image-input label:hover i {
      animation: shake .35s;
   }

   .image-input img {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 180px;
      height: 180px;
   }

   .image-input span {
      display: none;
      text-align: center;
      cursor: pointer;
   }

   @keyframes shake {
      0% {
         transform: rotate(0deg);
      }

      25% {
         transform: rotate(10deg);
      }

      50% {
         transform: rotate(0deg);
      }

      75% {
         transform: rotate(-10deg);
      }

      100% {
         transform: rotate(0deg);
      }
   }

   .image-input a{
      display: none;
      visibility: hidden;
   }
   .image-input{
      font-size: 0px;
   }

   

   .profile_pic {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 180px;
      height: 180px;
      border-radius: 50%;
   }

   .login-cta {
      color: var(--white);
      text-decoration: none;
      border: 1px solid var(--login-cta-hover);
      margin: 25px 0 35px;
      background: var(--login-cta-hover);
   }

   .login-cta:hover {
      background: var(--login-cta-hover);
   }

   .rounded-button {
      display: flex;
      width: 60%;
      margin-left: 15%;
      text-decoration: none;
      border-radius: 50px;
      padding: 13px 20px;
      box-sizing: border-box;
      justify-content: center;
      font-size: 14px;
      font-weight: 500;
      align-items: center;
      transition: linear 0.2s;
   }

   .rounded-button:hover {
      box-shadow: 0px 0px 4px 0px var(--grey);
   }

   h5 {
      width: 100%;
      text-align: left;
      border-bottom: 1px solid #000;
      line-height: 0.1em;
      margin: 10px 0 0px;
   }

   h5 span {
      background: #fff;
      padding: 0 10px;
   }

   @media only screen and (min-width: 799px) {
      .container {
         width: 50rem;
      }
   }

   @media only screen and (max-width: 500px) {
      .container {
         width: 100%;
      }
   }

   .container input:focus {
      outline: none;
      border: 1px solid var(--primary-color);
   }

   .container input {
      padding: 13px 20px;
      box-sizing: border-box;
      border: 1px solid var(--grey);
      border-radius: 50px;
      font-family: sans-serif;
      font-weight: 500;
      font-size: 14px;
      color: var(--text);
      transition: linear 0.2s;
      width: 100%;
   }
   .container select {
      padding: 13px 20px;
      box-sizing: border-box;
      border: 1px solid var(--grey);
      border-radius: 50px;
      font-family: sans-serif;
      font-weight: 500;
      font-size: 14px;
      color: var(--text);
      transition: linear 0.2s;
      width: 100%;
   }


   .container input ::-webkit-input-placeholder {
      color: var(--placeholder);
      font-weight: 300;
      font-size: 14px;
   }

   .form-control:focus {
      box-shadow: none;
   }

   span {
      background: var(--white);
      z-index: 1;
      position: relative;
      padding: 0 10px;
      font-size: 14px;
   }
   #cke_id_content[style*="width: 835px"] {
      width: auto !important;
   }

   .cke_reset {
      width: 100% !important;
   }

   @media only screen and (max-width: 500px) {
      #cke_id_content[style*="width: 835px"] {
         width: auto !important;
      }

      .cke_reset {
         width: 100% !important;
      }
   }
</style>
{% endblock content %}


{% block script %}

<script>
   $('#id_book_cover').on('change', function () {
      $input = $(this);
      if ($input.val().length > 0) {
         fileReader = new FileReader();
         fileReader.onload = function (data) {
            $('.image-preview').attr('src', data.target.result);
         }
         fileReader.readAsDataURL($input.prop('files')[0]);
         $('.image-button').css('display', 'none');
         $('.image-preview').css('display', 'block');
         $('.change-image').css('display', 'block');
      }
   });

   $('.change-image').on('click', function () {
      $control = $(this);
      $('#id_book_cover').val('');
      $preview = $('.image-preview');
      $preview.attr('src', '');
      $preview.css('display', 'none');
      $control.css('display', 'none');
      $('.image-button').css('display', 'block');
   });
</script>

{% endblock script %}